config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :cards  

  resources :users
  get 'users/show', to: "users#show"
  
  root to: "home#index"

  get "/buy/:card_id", to: "checkout#buy", as: "buy"
  get "/success", to: "checkout#success", as: "success"
  get "/cancel", to: "checkout#cancel", as: "cancel"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    
    resourcify

    belongs_to :user, dependent: :destroy
    has_one :genset, dependent: :destroy
    has_one :card_condition, dependent: :destroy

    has_one_attached :card_image, dependent: :purge

    validates :title, presence: { message: "Please add a Title"}
    validates :number, presence: { message: "Please add the Card Number"}
    validates :price, presence: { message: "Please add a Price to your Card"}
    
end

app/models/card_condition.rb
class CardCondition < ApplicationRecord
    has_many :cards
end

app/models/genset.rb
class Genset < ApplicationRecord
    has_many :cards
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_user_role
  rolify
  has_many :cards, dependent: :destroy
  has_one :role
  # has_one :account
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  #new user role
  def set_user_role
    self.add_role(:user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     

    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :not_allowed


    private

    def not_allowed 
        flash[:alert] = "Sorry! You're not allowed to do that!"
        redirect_to(request.referrer || root_path)
    end


    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    before_action :check_authorization, except: [:index, :show, :new, :create]
    before_action :find_card, only: [:update, :edit, :show, :destroy]
    before_action :setup_genset_and_card_condition, only: [:new, :edit, :show, :create]


    def index
        @cards = Card.order(title: :asc)
        @gensets = Genset.all
        @card_conditions = CardCondition.all
    end
    
    def new 
        @card = Card.new 
        
    end

    def create
        @card = Card.new(card_params)
        @card.user_id = current_user.id
        begin
            @card.save!
            redirect_to card_path(@card.id)
        rescue 
            flash.now[:errors] = @card.errors.messages.values.flatten
            render 'new'
        end
    end 

    def edit 
        begin

        rescue 
            
        end
    end

    #need to add flash error for update

    def update
        @card.update(card_params)
        redirect_to card_path(@card.id)
    end

    def destroy 
        @card.delete
        redirect_to cards_path
    end

    def show 
        begin
            @user = current_user
            @genset = Genset.find(@card.genset_id)
            @card_condition = CardCondition.find(@card.card_condition_id)
        rescue 
            redirect_to user_session_path
        end
    end

    def card_params
        params.require(:card).permit(:title, :number, :price, :genset_id, :card_condition_id, :card_image)
    end

    def setup_genset_and_card_condition
        @genset = Genset.order(:id)
        @card_condition = CardCondition.order(:id)
    end

    def find_card
        @card = Card.find(params[:id])
    end

    def check_authorization
        @card = find_card
        authorize @card
    end
  

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    
    def create
        
    end

    def buy 
        Stripe.api_key = ENV['STRIPE_SECRET_KEY']
        
        # 'sk_test_51JzDGfB3SnMhuojcOdMVnMKn4BLrIstw1i9Mn2BFgRhy00hn31wr976NU5HOjE8Gm5K0ah8JuE7H83abqrcGb6FM00AeiKZzhA'

        card = Card.find(params[:card_id])

        line_item = {
            price_data: {
                currency: 'aud',
                product_data: {
                    name: card.title,
                },
                unit_amount: card.price * 100
            },
            quantity: 1,
        }

        session = Stripe::Checkout::Session.create({
            line_items: [line_item],
            mode: 'payment',
            success_url: success_url + "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url: cancel_url + "?session_id={CHECKOUT_SESSION_ID}",
        })

          redirect_to session.url 
    end

def success 

end 

def cancel 

end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @user_cards = @user.cards
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_cardform.html.erb
<%= form_with model: @card do |f| %>

<p>
    <%= f.label :image %>
    <%= f.file_field :card_image %>
</p>
<p>
    <%= f.label :title %>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :card_number %>
    <%= f.number_field :number, in: 1..151 %>
</p>

<p>
    <%= f.label :price %>
    <%= f.number_field :price, in: 1..100000 %>
</p>
<p>
<p>
    <%= f.label :set %>
    <%= f.collection_select :genset_id, @genset, :id, :set %>
</p>
<p>
    <%= f.label :condition %>
    <%= f.collection_select :card_condition_id, @card_condition, :id, :condition %>
</p>
    <%= f.submit btn %>
</p>

<% end %>

app/views/cards/destroy.html.erb
<h1>Destroy</h1>

app/views/cards/edit.html.erb
<h1>Edit</h1>

<%= render 'cardform', btn: "Save changes!" %>

app/views/cards/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <title>Cards</title>
</head>
<body>
    <header class="page-header">
        <nav>
            <ul>
                 <a href="/"><li>Home</li></a> 
                 <a href="/cards"><li>Listings</li></a>
            </ul>
        </nav>
    </header>
    <div class="container listings-container">
        <div class="listings-content">
            <h1 class="page-heading listings-heading">Listings</h1>

            <div class="cards-links">
                <button class="btn-primary create-btn"><%= link_to "Create a Listing", new_card_path%></button>
            </div>

            <div class="cards-container">
                <% @cards.each do |card|  %>
                    <div class="card-content">
                        <%= cl_image_tag card.card_image.key, crop: :scale, cloud_name: "dle1j6d3x" if card.card_image.attached? %>
                        <div class="card-text-container">
                            <h3 class="card-heading">Card:</h3>
                            <h3 class="card-title"><%= link_to card.title, card_path(card.id) %></h3>
                        </div>
                        <div class="card-text-container">
                            <h3 class="card-heading">Set:</h3>
                            <h3 class="card-title"><%= @gensets.find(card.genset_id).set %></h3>
                        </div>
                        <div class="card-text-container">
                            <h3 class="card-heading">Condition:</h3>
                            <h3 class="card-title"> <%= @card_conditions.find(card.card_condition_id).condition %> </h3>
                        </div>
                        <div class="card-text-container">
                            <h3 class="card-heading">Price:</h3>
                            <h3 class="card-title">$<%= card.price %> </h3>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</body>
</html>

app/views/cards/new.html.erb
<h1>New Listing</h1>

<%= render 'cardform', btn: "Create Card!" %>

app/views/cards/show.html.erb
<header class="page-header">
    <nav>
        <ul>
             <a href="/"><li>Home</li></a> 
             <a href="/cards"><li>Listings</li></a>
        </ul>
    </nav>
</header>

<div class="container show-container">
    <div class="card-content">
        <%if @card.card_image.attached?%>
        <%= image_tag @card.card_image, crop: :scale, width: 240 %>
        <% end %>
        <div class="text-content">
            <h1 class="card-heading show-heading"><%= @card.title %></h1> 
            <div class="card-text-container">
                <h3 class="card-heading">Set:</h3> 
                <h3 class="card-title"><%= @genset.set %></h3>
            </div>
            <div class="card-text-container">
                <h3 class="card-heading">Card Number:</h3> 
                <h3 class="card-title"><%= @card.number %></h3>
            </div>
            <div class="card-text-container">
                <h3 class="card-heading">Condition:</h3> 
                <h3 class="card-title"><%= @card_condition.condition %></h3>
            </div>
            <div class="card-text-container">
                <h3 class="card-heading">Seller:</h3> 
                <h3 class="card-title"><%= @card.user.username %> </h3>
            </div>
            <div class="card-text-container">
                <h3 class="card-heading">Price:</h3> 
                <h3 class="card-title">$<%= @card.price %> </h3>
            </div>
        </div>
    </div>
    <div class="show-links-container">
        <button class="btn-primary back-btn">
            <%= link_to "Back to Listings", cards_path  %>
        </button>

        <% if @user.id != @card.user_id %>
        <button class="btn-primary buy-btn" type="submit"> 
            <%= link_to "Buy Card", buy_path(@card.id) %>
        </button>
        <% end %>

        <% if policy(@card).update? %>           
                <%= link_to "Edit", edit_card_path(@card), class: "btn-primary edit-btn" %>
        <% end %>
        <% if policy(@card).destroy? %>
            <button class="btn-primary delete-btn">
                <%= link_to "Delete Card", @card, method: :delete, data: {confirm: "Are you sure you want to delete this Card?"}  %>
            </button>
        <% end %>
    </div>
</div>

<!-- <h3>Description: ##add message field so users can add anything else they want to say about the card## </h3> -->

app/views/cards/update.html.erb
<h1>Update</h1>

app/views/checkout/cancel.html.erb
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cancel</title>
</head>
<body>
    <header class="page-header">
        <nav>
            <ul>
                 <a href="/"><li>Home</li></a> 
                 <a href="/cards"><li>Listings</li></a>
            </ul>
        </nav>
    </header>
    <div class="success-cancel-page-content page-hero">
        <h1 class="success-cancel-heading" >Successfully cancelled order!</h1>
        <h2 class="cancel-subheading">Sorry to see you cancel, please email us at help@help.com if we can be of any assistance</h2>
        <button class="btn-primary back-btn">
            <%= link_to "Back to Listings", cards_path  %>
        </button>
    </div>
</body>
</html>

app/views/checkout/success.html.erb
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>
<body>
    <header class="page-header">
        <nav>
            <ul>
                 <a href="/"><li>Home</li></a> 
                 <a href="/cards"><li>Listings</li></a> 
                 <a href=""><li></li></a> 
            </ul>
        </nav>
    </header>
    <div class="success-cancel-page-content page-hero">
        <h1 class="success-cancel-heading">Succesfully purchased!</h1>
        <h2 class="success-cancel-subheading"> YAY!</h2>
        <button class="btn-primary back-btn">
            <%= link_to "Back to Listings", cards_path  %>
        </button>
    </div>
</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../assets/stylesheets/home.css">
    <title>Home</title>
</head>
<body>
    <header class="page-header">
        <nav>
            <ul>
                 <a href="/"><li>Home</li></a> 
                 <a href="/cards"><li>Listings</li></a>
            </ul>
        </nav>
    </header>
    <div class="container page-hero">
        <div class="page-hero-content">
            <h1 class="home-page-heading">Complete your Gen 1 Pokémon Card set!</h1>
            <h2>Wether you're looking to complete that set you started as a kid or looking to sell your collection, you've found the right place. This is a place dedicated to buying and selling generation 1 cards! We hope you find what you're looking for :)
            </h2>
    </div>
    </div>

    
    
</body>
</html>

app/views/layouts/_usernav.html.erb
<section class="usernav">
    <% if user_signed_in? %>

    <%= current_user.username %>
    |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>

    <% else %>

    <%= link_to 'Login', new_user_session_path %>
    |
    <%= link_to 'Signup', new_user_registration_path %>

    <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiaKoenigT2a2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:errors] %>
    <section class="error-message">
      <% flash[:errors].each do |error| %>
      <h3> <%= error %> </h3>
      <% end %>
    </section>
    <% end %>

    <%= render 'layouts/usernav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 class="account-heading">Welcome! <%= @user.username %></h1>

    <p>Your Listings</p>

    <% @user_cards.each do |card| %>
        <%= link_to card.title, card_path(card) %>
        <% end %>

</body>
</html>